### ISSUE TITLE
Broken Syllabus Link - Error 404

### ISSUE THREAD

**Issue by nrust6** [BYU-IS-Media/independent_study#166] opened 2017-03-15 15:58 UTC
https://is.byu.edu/description/GOVT-046-200

Syllabus is temporarily unavailable on product description page.

**Comment by TrevinAvery** [comment] 2017-03-27 14:09
Duplicate of https://github.com/BYU-IS-Media/independent_study/issues/116

**Closed by TrevinAvery** 2017-03-27 14:09 UTC
Labels: duplicate
