### ISSUE TITLE
Find Testing Center Link

### ISSUE THREAD

**Issue by cheyen23** [BYU-IS-Media/independent_study#96] opened 2016-07-07 17:01 UTC
An error occurred as I followed the link to find a testing center location under the course tab.  Once it brought me to the web page it brought it up in the old website (http://isreg.byu.edu/site/support/find-testing-center.cfm)

**Comment by luke80** [comment] 2016-07-12 15:41
This is intended behavior, for now.

I'm marking this as an enhancement for the future.

**Closed by luke80** 2016-07-12 15:41 UTC
Labels: enhancement, wontfix
